name: causal_ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - numpy
  - pandas
  - xarray
  - zarr
  - fsspec
  - aiohttp
  - requests
  - geopandas
  - matplotlib
  - seaborn
  - scikit-learn
  - dask
  - netcdf4
  - h5netcdf
  - pip:
      - pycaret
      - econml
      - numba